config/routes.rb
Rails.application.routes.draw do
  resources :home
  root "home#index"
  get "origin", :to => "folders#root_directory", as: "origin"
  resources :folder_files
  resources :folders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/folder.rb
class Folder < ApplicationRecord
    has_many :folder_files
    belongs_to :parent, :class_name => "Folder", :foreign_key => "folder_child_id", :optional => true
   has_many :child_folders, :class_name => "Folder", :foreign_key => "folder_parent_id"
    


   
end

app/models/folder_file.rb
class FolderFile < ApplicationRecord
    belongs_to :folder, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/folder_files_controller.rb
class FolderFilesController < ApplicationController
  before_action :set_folder_file, only: [:show, :edit, :update, :destroy]

  # GET /folder_files
  # GET /folder_files.json
  def index
    @folder_files = FolderFile.all
  end

  # GET /folder_files/1
  # GET /folder_files/1.json
  def show
  end

  # GET /folder_files/new
  def new
    @folder_file = FolderFile.new
  end

  # GET /folder_files/1/edit
  def edit
  end

  # POST /folder_files
  # POST /folder_files.json
  def create
    @folder_file = FolderFile.new(folder_file_params)

    respond_to do |format|
      if @folder_file.save
        format.html { redirect_to @folder_file, notice: 'Folder file was successfully created.' }
        format.json { render :show, status: :created, location: @folder_file }
      else
        format.html { render :new }
        format.json { render json: @folder_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folder_files/1
  # PATCH/PUT /folder_files/1.json
  def update
    respond_to do |format|
      if @folder_file.update(folder_file_params)
        format.html { redirect_to @folder_file, notice: 'Folder file was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder_file }
      else
        format.html { render :edit }
        format.json { render json: @folder_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folder_files/1
  # DELETE /folder_files/1.json
  def destroy
    @folder_file.destroy
    respond_to do |format|
      format.html { redirect_to folder_files_url, notice: 'Folder file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder_file
      @folder_file = FolderFile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def folder_file_params
      params.fetch(:folder_file, {})
    end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]

  # GET /folders
  # GET /folders.json
  def index
    @folders = Folder.all
  end

  def root_directory
    @folder = Folder.find_or_create_by(root: true)
    @files = @folder.folder_files
    @folders = @folder.child_folders
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @files = @folder.folder_files
    @folders = @folder.child_folders
  end

  # GET /folders/new
  def new
    @folder = Folder.new
    @parent_folder = params[:folder_id]
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(folder_params)
    respond_to do |format|
      if @folder.save
        format.html { redirect_to home_path, notice: 'Folder was successfully created.' }
        format.json { render :show, status: :created, location: @folder }
      else
        format.html { render :new }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folders_url, notice: 'Folder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def folder_params
      params.fetch(:folder, {}).permit(:folder_name, :user_id, :folder_parent_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
   @title = "Source"
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.fetch(:home, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folder_files_helper.rb
module FolderFilesHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/folder_files/_form.html.erb
<%= form_with(model: folder_file, local: true) do |form| %>
  <% if folder_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder_file.errors.count, "error") %> prohibited this folder_file from being saved:</h2>

      <ul>
      <% folder_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/folder_files/edit.html.erb
<h1>Editing Folder File</h1>

<%= render 'form', folder_file: @folder_file %>

<%= link_to 'Show', @folder_file %> |
<%= link_to 'Back', folder_files_path %>

app/views/folder_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Folder Files</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folder_files.each do |folder_file| %>
      <tr>
        <td><%= link_to 'Show', folder_file %></td>
        <td><%= link_to 'Edit', edit_folder_file_path(folder_file) %></td>
        <td><%= link_to 'Destroy', folder_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Folder File', new_folder_file_path %>

app/views/folder_files/new.html.erb
<h1>New Folder File</h1>

<%= render 'form', folder_file: @folder_file %>

<%= link_to 'Back', folder_files_path %>

app/views/folder_files/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_folder_file_path(@folder_file) %> |
<%= link_to 'Back', folder_files_path %>

app/views/folders/_form.html.erb
<%= form_with(model: folder, local: true) do |form| %>
  <div class="actions">
  <div class="row">
    <%=form.label :folder_name%>
    <%=form.text_field :folder_name %>
  </div>
  <%= form.hidden_field :folder_parent_id, value: @parent_folder%>
<br>

    <%= form.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/new.html.erb
<div class="container">
<h1>New Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Back', folders_path %>
</div>

app/views/folders/root_directory.html.erb
<div class="container">
<h1> Root </h1>
<br>
    <div class="row">
        <button id="new-btn"> New </button>
    </div><br>
    <div class="row" style= "display:none;" id="hidden-form">
        <form>
            <%= link_to "New Folder", new_folder_path(folder_id: @folder.id)%><br>
            <%= link_to "New File", new_folder_file_path(folder_id: @folder.id)%>
        </form>
    </div>
    <% @files.each do |file|%>
        <%= file.file_name%>
    <%end%>
    
    <% @folders.each do |folder|%>
        <div class="col-md-2">
        <div class="row">
            <%= link_to image_tag("/public/images/folder.png"), folder_path(folder)%>
        </div>
        <div class="row">
            <%= label_tag folder.folder_name%>
        </div>
        </div>
    <%end%>
</div>

app/views/folders/show.html.erb
<div class="container">
<br>
    <div class="row">
        <button id="new-btn"> New </button>
    </div><br>
    <div class="row" style= "display:none;" id="hidden-form">
        <form>
            <%= link_to "New Folder", new_folder_path(folder_id: @folder.id)%><br>
            <%= link_to "New File", new_folder_file_path(folder_id: @folder.id)%>
        </form>
    </div>
    <% @files.each do |file|%>
        <%= file.file_name%>
    <%end%>
    
    <% @folders.each do |folder|%>
        <div class="col-md-2">
        <div class="row">
            <%= link_to image_tag("/public/images/folder.png"), folder_path(folder)%>
        </div>
        <div class="row">
            <%= label_tag folder.folder_name%>
        </div>
        </div>
    <%end%>
</div>

app/views/home/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/home/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/home/index.html.erb
<div class="container">

<h1>Home</h1>
<div class="row">
  <%=link_to "Create a new folder", new_folder_path%>
</div>

<div class="row">
  <%= link_to "Create new file", new_folder_file_path%>
</div>

</div>

app/views/home/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/home/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Source</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>